package domain

import "errors"

// Tipos de reembolso
const (
	RefundTypeFull    = "FULL"
	RefundTypePartial = "PARTIAL"
)

var (
	ErrUserNotFound                = errors.New("user not found")
	ErrUserAlreadyExists           = errors.New("user already exists")
	ErrInvalidCredentials          = errors.New("invalid credentials")
	ErrInvalidToken                = errors.New("invalid token")
	ErrTokenExpired                = errors.New("token expired")
	ErrSessionExpired              = errors.New("session expired")
	ErrUnauthorized                = errors.New("unauthorized")
	ErrForbidden                   = errors.New("forbidden")
	ErrInvalidInput                = errors.New("invalid input")
	ErrInternal                    = errors.New("internal server error")
	ErrKYCAlreadySubmitted         = errors.New("kyc already submitted")
	ErrKYCAlreadyApproved          = errors.New("kyc already approved")
	ErrKYCInManualReview           = errors.New("kyc in manual review")
	ErrKYCNotFound                 = errors.New("kyc not found")
	ErrKYCNotApproved              = errors.New("kyc not approved")
	ErrLivenessCheckFailed         = errors.New("liveness check failed")
	ErrDriverKYCRequired           = errors.New("driver kyc required")
	ErrDriverNotActive             = errors.New("driver not active")
	ErrMaxRetriesExceeded          = errors.New("max retries exceeded")
	ErrVehicleNotFound             = errors.New("vehicle not found")
	ErrVehicleAlreadyExists        = errors.New("vehicle already exists")
	ErrVehicleNotAvailable         = errors.New("vehicle not available")
	ErrVehicleAlreadyVerified      = errors.New("vehicle already verified")
	ErrInvalidVehicleData          = errors.New("invalid vehicle data")
	ErrSeatsExceedCapacity         = errors.New("seats exceed capacity")
	ErrTripNotFound                = errors.New("trip not found")
	ErrTripFull                    = errors.New("trip full")
	ErrTripAlreadyStarted          = errors.New("trip already started")
	ErrTripAlreadyCompleted        = errors.New("trip already completed")
	ErrTripAlreadyCancelled        = errors.New("trip already cancelled")
	ErrTripCannotBeCancelled       = errors.New("trip cannot be cancelled")
	ErrCannotCancelStartedTrip     = errors.New("cannot cancel started trip")
	ErrDepartureTimeMustBeFuture   = errors.New("departure time must be in the future")
	ErrInvalidTripStatusChange     = errors.New("invalid trip status change")
	ErrBookingNotFound             = errors.New("booking not found")
	ErrBookingAlreadyExists        = errors.New("booking already exists")
	ErrBookingCannotBeCancelled    = errors.New("booking cannot be cancelled")
	ErrBookingAlreadyCancelled     = errors.New("booking already cancelled")
	ErrCannotBookOwnTrip           = errors.New("cannot book own trip")
	ErrInvalidSeatCount            = errors.New("invalid seat count")
	ErrInsufficientSeats           = errors.New("insufficient seats")
	ErrOverlappingTripBooking      = errors.New("overlapping trip booking")
	ErrPriceExceedsCapPrice        = errors.New("price exceeds cap price")
	ErrInvalidBookingStatus        = errors.New("invalid booking status")
	ErrBookingExpired              = errors.New("booking expired")
	ErrInsufficientBalance         = errors.New("insufficient balance")
	ErrEscrowNotFound              = errors.New("escrow transaction not found")
	ErrEscrowAlreadySettled        = errors.New("escrow transaction already settled")
	ErrPaymentFailed               = errors.New("payment failed")
	ErrInvalidRefundAmount         = errors.New("invalid refund amount")
	ErrReviewNotFound              = errors.New("review not found")
	ErrReviewAlreadyExists         = errors.New("review already exists")
	ErrDuplicateReview             = errors.New("duplicate review")
	ErrReviewSelfNotAllowed        = errors.New("review self not allowed")
	ErrInvalidRating               = errors.New("invalid rating")
	ErrTripNotCompletedForReview   = errors.New("trip not completed for review")
	ErrDisputeNotFound             = errors.New("dispute not found")
	ErrDisputeAlreadyExists        = errors.New("dispute already exists")
	ErrInvalidDisputeData          = errors.New("invalid dispute data")
	ErrDisputeSelfNotAllowed       = errors.New("dispute self not allowed")
	ErrDisputeAlreadyResolved      = errors.New("dispute already resolved")
	ErrInvalidRouteCoordinates     = errors.New("invalid route coordinates")
	ErrInsufficientRoutePoints     = errors.New("insufficient route points")
)
