package domain

import "errors"

var (
	ErrUserNotFound             = errors.New("user not found")
	ErrUserAlreadyExists        = errors.New("user already exists")
	ErrInvalidCredentials       = errors.New("invalid credentials")
	ErrInvalidToken             = errors.New("invalid token")
	ErrTokenExpired             = errors.New("token expired")
	ErrUnauthorized             = errors.New("unauthorized")
	ErrForbidden                = errors.New("forbidden")
	ErrInvalidInput             = errors.New("invalid input")
	ErrInternal                 = errors.New("internal server error")
	ErrKYCAlreadySubmitted      = errors.New("kyc already submitted")
	ErrKYCNotFound              = errors.New("kyc not found")
	ErrKYCNotApproved           = errors.New("kyc not approved")
	ErrVehicleNotFound          = errors.New("vehicle not found")
	ErrVehicleAlreadyExists     = errors.New("vehicle already exists")
	ErrTripNotFound             = errors.New("trip not found")
	ErrTripFull                 = errors.New("trip full")
	ErrTripAlreadyStarted       = errors.New("trip already started")
	ErrTripAlreadyCompleted     = errors.New("trip already completed")
	ErrTripAlreadyCancelled     = errors.New("trip already cancelled")
	ErrBookingNotFound          = errors.New("booking not found")
	ErrBookingAlreadyExists     = errors.New("booking already exists")
	ErrBookingCannotBeCancelled = errors.New("booking cannot be cancelled")
	ErrInsufficientBalance      = errors.New("insufficient balance")
	ErrEscrowNotFound           = errors.New("escrow transaction not found")
	ErrReviewNotFound           = errors.New("review not found")
	ErrReviewAlreadyExists      = errors.New("review already exists")
	ErrDisputeNotFound          = errors.New("dispute not found")
	ErrDisputeAlreadyExists     = errors.New("dispute already exists")
)
